# _config.yml

title: Akash Raj
description: >-
  Portfolio of Akash Raj — aspiring Software Engineer, Mechanical Engineering undergraduate, and full-stack learner.
baseurl: ""
url: "https://akasr.github.io"

remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme

# Social links (optional)
github:
  is_project_page: false
  owner_url: https://github.com/akasr

# SEO & metadata
author: Akash Raj
email: ebookexer@gmail.com
