# _config.yml

title: Akash Raj
description: >-
  Aspiring Software Engineer, Mechanical Engineering undergraduate, and full-stack learner.
baseurl: ""
url: "https://akasr.github.io"

theme: jekyll-theme-dinky

# Social links (optional)
github:
  is_project_page: false
  owner_url: https://github.com/akasr

# SEO & metadata
author: Akash Raj
email: ebookexer@gmail.com
